name = "lapce-go"
version = "0.0.1"
author = "panekj"
display-name = "Go (gopls)"
description = "Go for Lapce using gopls"
wasm = "bin/lapce-go.wasm"

[activation]
language = ["go"]
workspace-contains = ["*/go.mod"]
